# Generated by Django 4.1.3 on 2023-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='viewed',
            field=models.IntegerField(default=1),
        ),
    ]
